services:
  - type: web
    name: webhook-repo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://webhook_user:Webhook123@cluster0.5v8i2rv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: webhook_db
      - key: COLLECTION_NAME
        value: events
